@baseUrl = http://localhost:3000/api/reviews

### Get all reviews
GET {{baseUrl}}
Content-Type: application/json

###

### Get a specific review
GET {{baseUrl}}/1
Content-Type: application/json

###

### Create a review
POST {{baseUrl}}
Content-Type: application/json

{
  "rating": 5,
  "user_id": 101,
  "field_id": 101,
  "review_text": "Great field!"
}

###

### Update a review
PUT {{baseUrl}}/101
Content-Type: application/json

{
  "rating": 4,
  "review_text": "Good field, but could be better."
}

###

### Delete a review
DELETE {{baseUrl}}/1

###
