@baseUrl = http://13.229.202.42:5000/api/amenities

### Get all amenities
GET {{baseUrl}}/
Content-Type: application/json

{
  
}

### Get an amenity
GET {{baseUrl}}/1
Content-Type: application/json

{
  
}

### Create an amenity
POST {{baseUrl}}/
Content-Type: application/json

{
  "amenity_name": "Boots"
}

### Update an amenity
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "amenity_name": "High-Speed WiFi"
}

### Delete an amenity
DELETE {{baseUrl}}/1
Content-Type: application/json

{

}
