@baseUrl = http://13.229.202.42:5000/api/bookings

### Get all bookings
GET {{baseUrl}}/
Content-Type: application/json

{

}

### Get a booking
GET {{baseUrl}}/3
Content-Type: application/json

{

}

### Create a booking
POST {{baseUrl}}/
Content-Type: application/json

{
  "user_id": 17,
  "field_id": 2,
  "start_datetime": "2025-1-07T6:00:00Z",
  "duration": 60,
  # "lfg_id": 7,
  "current_players": 0
}

### Update a booking
PUT {{baseUrl}}/8
Content-Type: application/json

{
  "user_id": 17,
  "status": "cancelled",
  "field_id": 2,
  "start_datetime": "2025-1-07T6:00:00Z",
  "duration": 60,
  "lfg_id": 7,
  "current_players": 0
}

### Delete a booking
DELETE {{baseUrl}}/1
Content-Type: application/json

{

}
