@baseUrl = http://13.229.202.42:5000/api/booking_schedule

### Create a booking schedule
POST {{baseUrl}}/
Content-Type: application/json

{
  "booking_id": 2,
  "status": "available"
}

### Update a booking schedule
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "booking_id": 1,
  "status": "booked"
}

### Delete a booking schedule
DELETE {{baseUrl}}/1
Content-Type: application/json

{

}
