@baseUrl = http://13.229.202.42:5000/api/field_amenities

### Get all field amenities
GET {{baseUrl}}/
Content-Type: application/json

{

}

### Get a field amenity
GET {{baseUrl}}/
Content-Type: application/json

{

}

### Create a field amenity
POST {{baseUrl}}/
Content-Type: application/json

{
  "field_id": 3,
  "amenity_id": 4
}

### Update a field amenity
PUT {{baseUrl}}/
Content-Type: application/json

{
  "old_data": {
    "field_id": 1,
    "amenity_id": 1
  },
  "new_data": {
    "field_id": 2,
    "amenity_id": 2
  }
}

### Delete a field amenity
DELETE {{baseUrl}}/
Content-Type: application/json

{
  "field_id": 1,
  "amenity_id": 1
}
