@baseUrl = http://13.229.202.42:5000/api/lfgs

### Get all LFGs
GET {{baseUrl}}/
Content-Type: application/json

{
  
}

### Get a LFG
GET {{baseUrl}}/1
Content-Type: application/json

{
  
}

### Create an LFG
POST {{baseUrl}}/
Content-Type: application/json

{
  "required_players": 9
}

### Update an LFG
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "required_players": 3,
  "status": "closed"
}

### Delete an LFG
DELETE {{baseUrl}}/1
Content-Type: application/json

{

}
