@baseurl = http://13.229.202.42:5000/api/notifications

### Create a notification

POST {{baseurl}}
Content-Type: application/json

{
  "user_id": 1,
  "message": "Your booking has been confirmed."
}

###

### Update a notification
PUT http://localhost:5000/api/notifications/1
Content-Type: application/json

{
  "user_id": 1,
  "message": "Your booking has been updated."
}

###

### Delete a notification
DELETE http://localhost:5000/api/notifications/1

###
