@baseUrl = http://13.229.202.42:5000/api/users

### Get all users
GET {{baseUrl}}/
Content-Type: application/json

{

}

### Get a user
GET {{baseUrl}}/1
Content-Type: application/json

{
  
}

### Create a user
POST {{baseUrl}}/
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "password123"
}

### Create a vendor user
POST {{baseUrl}}/
Content-Type: application/json

{
  "name": "Vendor User",
  "email": "vendor@example.com",
  "password": "vendorpassword",
  "phone": "1234567890",
  "user_role": "vendor"
}

### Update a user
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "name": "John Smith",
  "email": "john.smith@example.com",
  "password": "newpassword123",
  "phone": "0987654321"
}

### Delete a user
DELETE {{baseUrl}}/1
Content-Type: application/json

{

}
