@baseUrl = http://localhost:5000/api/users

### Get all users
GET {{baseUrl}}/
Content-Type: application/json

{

}

### Get a user
GET {{baseUrl}}/1
Content-Type: application/json

{

}

### Create a user
POST {{baseUrl}}/
Content-Type: application/json

{
  "name": "Nor Binti Mohd Ahmad",
  "email": "nor.ahmad@uni.edu.my",
  "password": "987654321",
  "phone": "01111778899"
}

### Create a vendor user
POST {{baseUrl}}/
Content-Type: application/json

{
  "name": "Amr Smith",
  "email": "Amr.smith@vender.co",
  "password": "pray-for-gaza",
  "phone": "01122334455",
  "user_role": "vendor"
}

### Update a user
PUT {{baseUrl}}/2
Content-Type: application/json

{
  "name": "Amr Smith",
  "email": "Amr.smith@example.co",
  "password": "pray-for-gaza",
  "phone": "01122334455"
}

### Delete a user
DELETE {{baseUrl}}/1
Content-Type: application/json

{

}
